### ISSUE TITLE
Looking for Co-maintainers

### ISSUE THREAD

**Issue by mgattozzi** [github-rs/github-rs#126]
My life outside of work has really gotten more busy than I like and as such many PRs
and issues have been languishing away as currently I'm the creator and sole maintainer
of this repo. I think this is a mistake given that there are currently 7 outstanding PRs
and others looking to depend on this crate for their projects.

Because I'm doing some stuff outside of work that will be eating up a lot of my free time
(I can't legally talk about what it is yet) I'd like to open up this issue to let people know I'm
looking for some people to help maintain and accept PRs, specifically those that can help extend
functionality and add more endpoints.

If you're interested in helping out please shoot me an email at mgattozzi@gmail.com. If you
prefer to communicate in some other way and are interested you can leave a comment below
as well. If you wish to use PGP as part of your communication with me you can find my key [here](https://keybase.io/mgattozzi).

**Comment by mgattozzi** [comment]
I don't think I announced this yet but @Dylan-DPC will be helping me comaintain this repo, as I have a lot of stuff going on with the wasm working group as well as my own personal work as mentioned before. I'm going to keep this issue open for now in case anyone else wants to help! Thanks again @Dylan-DPC for volunteering :)

**Comment by Dylan-DPC** [comment]
We now have an organisation that is maintaining the crate, so closing this
