### ISSUE TITLE
Current release still using old dependency

### ISSUE THREAD

**Issue by enricostano** [github-rs/github-rs#147]
Hi, I see from https://github.com/mgattozzi/github-rs/pull/132 that you upgraded `hyper-rustls` to `0.12.0` but the `github-rs` current release `0.6.1` is still pointing to `hyper-rustls v0.11.0`.

```
package `ring v0.12.1`
    ... which is depended on by `webpki v0.17.0`
    ... which is depended on by `rustls v0.11.0`
    ... which is depended on by `hyper-rustls v0.11.0`
    ... which is depended on by `github-rs v0.6.1`
    ... which is depended on by `volantino v0.1.0 (file:///home/enrico/dev/volantino.rs)`
links to native library `ring-asm`
```
Can you please issue a new release to get the latest changes? Thanks!

**Comment by enricostano** [comment]
In any case even pointing to the git repo `ring` doesn't compile: https://gist.github.com/enricostano/c08dd106934cce9918e13ee93dcbaf81

Thanks for working on this!

**Comment by mgattozzi** [comment]
Hey! I was on vacation so I just haven't had time to do updates, but with hyper 0.12 out I think I can roll this in as part of an upgrade :)

**Comment by Mange** [comment]
Any update on this?

**Comment by Dylan-DPC** [comment]
The new release up, so this is fixed. Thanks
