### ISSUE TITLE
Please re-publish to Crates.io

### ISSUE THREAD

**Issue by joe-askattest** [github-rs/github-rs#150]
* 4 months ago a bug with `orgs` having the wrong name was fixed [here](https://github.com/mgattozzi/github-rs/commit/aceb611ff34a9e173ddac63fe6d9145edb751ab7)
 * The last time the crate was published was 6 months ago [here](https://crates.io/crates/github-rs)

So Crates.io still has the bug above.

Would it be possible to get this crate published again so that the version on crates.io is working?

**Comment by Dylan-DPC** [comment]
@joe-askattest Thanks. 

All we have to do is publish a new release right?

**Comment by joe-askattest** [comment]
@Dylan-DPC Yup. You will need to bump the version number first. Looking at the commit history it looks like new stuff is going out, so I'd bump it to `0.7.0` to indicate it's not just bug fixes.

Then `cargo publish`.

**Comment by Dylan-DPC** [comment]
@joe-askattest yeah thanks. I'm aware of the release process. Since you mentioned "get published again" I wasn't sure whether you meant a new release or the entire process all over again.

**Comment by joe-askattest** [comment]
Ah ok. Np.

**Comment by mgattozzi** [comment]
I've been real swampped with things and I kind of left this library by the wayside. I believe we can push a new version. I can do that today, but honestly I just don't have the capacity to be working on this much in terms of getting in bugfixes answering issues etc. It might also be good to look at [hubcaps](https://github.com/softprops/hubcaps) as an alternative.

**Comment by joe-askattest** [comment]
Thank you. The lack of structs being provided by `github-rs` has been a real pain point for me and Hubcaps solves this. So I will try it out.

It would still be great to get the `github-rs` crate updated.

**Comment by Dylan-DPC** [comment]
I can do it the release.

**Comment by shinzui** [comment]
@Dylan-DPC you get a chance to release?

**Comment by Dylan-DPC** [comment]
@shinzui oops. Will wait for #158 to be merged and then issue a release :+1:

**Comment by Mange** [comment]
Any update on this?

**Comment by dwijnand** [comment]
As a side note, it's a shame to have both two different libraries.  Are there any intentional differences?  I think it would be nice to pull in the same direction in one library 🙂

**Comment by Dylan-DPC** [comment]
Hey

We just released the new version (0.7.0) on crates.io. Sorry about the delays :)
