### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kornelski** [github-rs/github-rs#163]
This crates.io version of this crate currently doesn't work (in a new install without an old `Cargo.lock`), because its own dependencies have become incompatible with the outdated hyper:

> error: failed to select a version for the requirement `untrusted = "^0.5.1"`
  candidate versions found which didn't match: 0.6.2
  location searched: crates.io index
required by package `rustls v0.11.0`
    ... which is depended on by `hyper-rustls v0.11.0`
    ... which is depended on by `github-rs v0.6.1`

**Comment by mgattozzi** [comment]
I'm willing to give commit/maintainership rights as well cause I just do not have the time/capacity to maintain this currently.

**Comment by kornelski** [comment]
I'm happy to help

**Comment by kornelski** [comment]
ping

**Comment by brndnmtthws** [comment]
@mgattozzi I'd be willing to take over maintenance. I need this for a bot I'm working on for some of my other OSS projects.

**Comment by Dylan-DPC** [comment]
Sorry for the delay. Will try and have a release this week.

**Comment by kornelski** [comment]
@Dylan-DPC ping

**Comment by Dylan-DPC** [comment]
@kornelski was discussing with Matt. I am currently moving this repo to a new github organisation so that I can add you and others interested as co-maintainers and maybe the crate can get some traction from there. Will release once i'm done with that.

**Comment by kornelski** [comment]
@Dylan-DPC 	ping

**Comment by Dylan-DPC** [comment]
@kornelski yeah so before we do the release we need to do the following steps: 

1) update the repo to match the organisational change
2) provide a new encrypted token which fixes the issue of the build being broken at the moment

I'll try and get this done later today, but if anyone has time and wants to go ahead with it, feel free.

**Comment by kornelski** [comment]
I get the whole org changes thing, but currently the project is *dead*, and all it needs to work again is running `cargo publish` and pressing enter.

**Comment by brndnmtthws** [comment]
If you grant me the permissions, I can do it.

Who has access to crates.io for the deploy key?

**Comment by Dylan-DPC** [comment]
@brndnmtthws i'll do it no issues. just want to get somethings working before that.

**Comment by kennethlarsen** [comment]
Any updates on this?

**Comment by Dylan-DPC** [comment]
@kennethlarsen sorry about the delays. Pulled in the tests yesterday and ran them after fixing the token issue, but they were still failing so i'll look into it again today

**Comment by kornelski** [comment]
@Dylan-DPC Can you just run `cargo publish` on whatever is there already? The version on crates.io *doesn't even compile*, so anything is better than that.

**Comment by fairingrey** [comment]
@Dylan-DPC asked me to take a moment to help fix some of the issues in this crate, and I've wrapped up some of those fixes in https://github.com/github-rs/github-rs/pull/170.

Hopefully we can see a version bump soon after that's merged, but currently Travis is having trouble using OpenSSL to generate an AES key so it's not building properly. Sans that, however, if you pull and build my branch, you'll see that everything should (hopefully) work. I've run both sets of tests with the default `rustls` feature enabled and also with `rust-native-tls` enabled and they both pass just fine.

@kornelski You can use my branch temporarily while the new maintainers help bring this crate back up to speed. I understand the wait can be pretty annoying.

**Comment by Dylan-DPC** [comment]
@kornelski the new release is up on crates.io.
